---
- name: Configure Git
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    git_email: justinluong1@gmail.com
    git_name: Justin

  tasks:
    - name: Set Git Config
      shell: |
        git config --global user.email {{ git_email }}
        git config --global user.name {{ git_name }}
      ignore_errors: true

    - name: Configure Git Credential Storage
      command: "git config --global credential.helper store"
      ignore_errors: true