---
- name: Configure Git
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    git_email: jluong2@woolworths.com.au
    git_name: Justin

  tasks:
    - name: Set Git Config
      command: "git config --global user.email {{ git_email }} && git config --global user.name {{ git_name }}"
      ignore_errors: true

    - name: Configure Git Credential Storage
      command: "git config --global credential.helper store"
      ignore_errors: true